const { app, BrowserWindow } = require('electron')
const fs = require('node:fs'), path = require('node:path'), os = require('node:os'), assert = require('node:assert/strict')
const qa = path.resolve(process.argv[2]), state = JSON.parse(fs.readFileSync(path.join(qa, 'watch-ui-state.json'), 'utf8'))
const base = `http://127.0.0.1:${state.port}`, api = `/api/research/projects/${state.project_id}`
app.setPath('userData', fs.mkdtempSync(path.join(os.tmpdir(), 'zhishi-watch-render-')))
app.disableHardwareAcceleration()
const delay = ms => new Promise(resolve => setTimeout(resolve, ms))
app.whenReady().then(async () => {
  const errors = []; let win
  try {
    win = new BrowserWindow({ width:1450, height:1000, show:false, webPreferences:{offscreen:true, contextIsolation:true, nodeIntegration:false, sandbox:true} })
    win.webContents.on('console-message', (_e, level, message) => { if (level >= 2 && !message.includes('Electron Security Warning')) errors.push(message) })
    const js = code => win.webContents.executeJavaScript(code, true)
    async function wait(code) { for (let i=0;i<400;i++) { if (await js(code)) return; await delay(100) } throw Error('Timeout '+code) }
    const click = selector => js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e||e.disabled)throw Error('Unavailable '+${JSON.stringify(selector)});e.click()})()`)
    const input = (selector, value) => js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))})()`)
    const snapshot = async name => { await js("document.querySelector('.research-watch').scrollIntoView({block:'start'})"); await delay(400); fs.writeFileSync(path.join(qa,name+'.png'),(await win.webContents.capturePage()).toPNG()) }
    const read = () => js(`fetch('${api}/watch').then(r=>r.json())`)
    await win.loadURL(base+`/#/research?project=${state.project_id}`)
    await wait("!!document.querySelector('[data-watch-edit]')")
    assert(await js("document.querySelector('.research-watch').textContent.includes('未开启')"))
    await click('[data-watch-edit]')
    await click('[data-watch-enabled]')
    await click('[data-watch-save]')
    await wait("document.querySelector('.research-watch [role=alert]')?.textContent.includes('检索词')")
    await input('[data-watch-queries]', '公开教程 更新')
    await input('[data-watch-frequency]', 'weekly')
    await input('[data-watch-weekday]', '2')
    await input('[data-watch-time]', '08:45')
    await input('[data-watch-limit]', '2')
    await js("document.documentElement.dataset.theme='light'")
    await snapshot('watch-settings-light')
    await js("document.documentElement.dataset.theme='dark'")
    await snapshot('watch-settings-dark')
    win.setSize(900,1000); await delay(250)
    await snapshot('watch-settings-narrow')
    assert(await js('document.documentElement.scrollWidth<=innerWidth'))
    await click('[data-watch-save]')
    await wait("!!document.querySelector('[data-watch-run]')")
    let saved = await read()
    assert.deepEqual(saved.config.queries,['公开教程 更新'])
    assert.equal(saved.config.frequency,'weekly'); assert.equal(saved.config.weekday,2)
    assert.equal(saved.config.time,'08:45'); assert.equal(saved.config.max_sources,2)
    await click('[data-watch-run]')
    await wait("document.querySelector('.research-watch .run strong')?.textContent==='资料有更新' && !document.querySelector('[data-watch-run]')?.disabled")
    saved = await read()
    assert.equal(saved.runs.length,1); assert.equal(saved.runs[0].sources.filter(s=>s.changed).length,2)
    await click('.research-watch .run summary')
    await snapshot('watch-results-dark')
    await click('.research-watch .run a')
    await wait("document.querySelector('.material-reader pre')?.textContent.includes('更新教程')")
    await js("location.hash='/calendar'")
    await wait("!document.querySelector('.material-reader')")
    await click('.bell-wrap .bell')
    await wait("!!document.querySelector('.li-open') && [...document.querySelectorAll('.li-open')].some(e=>e.textContent.includes('查看资料跟进'))")
    await js("[...document.querySelectorAll('.li-open')].find(e=>e.textContent.includes('查看资料跟进')).click()")
    await wait(`location.hash.includes('project=${state.project_id}') && !!document.querySelector('[data-watch-run]')`)
    await click('[data-watch-run]')
    await wait("document.querySelector('.research-watch .run strong')?.textContent==='暂无变化' && !document.querySelector('[data-watch-run]')?.disabled")
    await click('[data-watch-pause]')
    await wait("!document.querySelector('[data-watch-run]') && document.querySelector('.research-watch').textContent.includes('未开启')")
    await win.reload()
    await wait("!!document.querySelector('[data-watch-edit]')")
    saved = await read(); assert(!saved.config.enabled); assert.equal(saved.runs.length,2)
    assert(!await js("!!document.querySelector('[data-watch-run]')"))
    await click('[data-watch-edit]'); await click('[data-watch-enabled]')
    await input('[data-watch-frequency]','daily'); await input('[data-watch-time]','09:15')
    await click('[data-watch-save]'); await wait("!!document.querySelector('[data-watch-run]')")
    assert.deepEqual(errors,[])
    fs.writeFileSync(path.join(qa,'watch-ui-result.json'), JSON.stringify({passed:true,checks:['default off','required public queries','weekly settings','light/dark/narrow','native run saves two materials','read returned snapshot','notification opens project','unchanged run','pause and reload','daily configuration'], errors},null,2))
    console.log('WATCH_NATIVE_UI_PASS'); app.exit(0)
  } catch (error) {
    console.error(error.stack)
    if (win) fs.writeFileSync(path.join(qa,'watch-ui-failure.png'),(await win.webContents.capturePage()).toPNG())
    fs.writeFileSync(path.join(qa,'watch-ui-failure.json'),JSON.stringify({error:String(error),errors},null,2))
    app.exit(1)
  }
})
