const {app,BrowserWindow}=require('electron')
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict')
const qa=path.resolve(process.argv[2]),state=JSON.parse(fs.readFileSync(path.join(qa,'calendar-state.json'),'utf8'))
const base=`http://127.0.0.1:${state.port}`,sleep=ms=>new Promise(r=>setTimeout(r,ms))
app.setPath('userData',fs.mkdtempSync(path.join(os.tmpdir(),'zhishi-calendar-render-')))
app.disableHardwareAcceleration()
app.whenReady().then(async()=>{
 const win=new BrowserWindow({width:1450,height:1000,show:false,webPreferences:{offscreen:true,contextIsolation:true,nodeIntegration:false,sandbox:true}})
 const errors=[],checks=[];let failPatch=false
 win.webContents.session.webRequest.onBeforeRequest({urls:[base+'/api/schedule/events/*']},(details,callback)=>callback({cancel:failPatch&&details.method==='PATCH'}))
 win.webContents.on('console-message',(_e,level,msg)=>{if(level>=2&&!msg.includes('Electron Security Warning')&&!msg.includes('ERR_BLOCKED_BY_CLIENT'))errors.push(msg)})
 const js=code=>win.webContents.executeJavaScript(code,true)
 async function wait(code){for(let i=0;i<200;i++){if(await js(code))return;await sleep(100)}throw Error('Timeout '+code)}
 async function fill(id,value){await js(`(()=>{const e=document.getElementById(${JSON.stringify(id)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))})()`)}
 async function open(title,selector='.course'){await wait(`[...document.querySelectorAll(${JSON.stringify(selector)})].some(e=>e.textContent.includes(${JSON.stringify(title)}))`);await js(`[...document.querySelectorAll(${JSON.stringify(selector)})].find(e=>e.textContent.includes(${JSON.stringify(title)})).click()`);await wait(`!!document.querySelector('#event-edit-title')`)}
 async function save(){await js(`document.querySelector('#event-edit-save').click()`);await wait(`document.querySelector('.event-editor [role="status"]')?.textContent.includes('已保存')`)}
 async function close(){await js(`document.querySelector('[aria-label="关闭详情"]').click()`);await wait(`!document.querySelector('#event-edit-title')`)}
 async function shot(name){await sleep(150);fs.writeFileSync(path.join(qa,name+'.png'),(await win.webContents.capturePage()).toPNG())}
 const get=id=>fetch(base+'/api/schedule/events/'+id).then(r=>r.json())
 try{
  await win.loadURL(base+'/#/calendar')
  await open('日历编辑验收')
  await fill('event-edit-title','已修改的行程');await fill('event-edit-start','10:30');await fill('event-edit-end','10:00')
  await js(`document.querySelector('#event-edit-save').click()`)
  await wait(`document.querySelector('.event-editor [role="alert"]')?.textContent.includes('结束时间')`)
  assert.equal((await get(state.single.id)).title,'日历编辑验收')
  await fill('event-edit-end','11:30');await fill('event-edit-location','新会议室');await fill('event-edit-notes','修改后备注');await fill('event-edit-category','meeting')
  failPatch=true;await js(`document.querySelector('#event-edit-save').click()`)
  await wait(`!!document.querySelector('.event-editor [role="alert"]')&&!document.querySelector('#event-edit-save').disabled`)
  assert.equal(await js(`document.querySelector('#event-edit-title').value`),'已修改的行程')
  assert.equal((await get(state.single.id)).title,'日历编辑验收')
  failPatch=false;await save();await shot('calendar-edit-light');await close()
  await wait(`[...document.querySelectorAll('.course')].some(e=>e.textContent.includes('已修改的行程'))`)
  const saved=await get(state.single.id)
  assert.deepEqual([saved.start_time,saved.end_time,saved.location,saved.notes,saved.category],['10:30','11:30','新会议室','修改后备注','meeting'])
  assert.deepEqual(saved.remind_offsets,[30]);checks.push('week edit validation, blocked request retains edits, retry updates all fields and visible calendar')
  await js(`document.querySelector('[data-mode="day"]').click()`);await open('已修改的行程')
  await fill('event-edit-start','');await fill('event-edit-end','')
  await js(`document.querySelector('#event-edit-save').click()`)
  await wait(`document.querySelector('.event-editor [role="alert"]')?.textContent.includes('改为全天')`)
  await fill('event-edit-reminder-time','09:00');await save();await close()
  assert.equal((await get(state.single.id)).start_time,null)
  checks.push('day view opens editor and converts event to all-day')
  await js(`document.querySelector('[data-mode="month"]').click()`);await open('已修改的行程','.entry')
  const changedDate=state.single.date.slice(0,8)+(state.single.date.endsWith('01')?'02':'01')
  await fill('event-edit-date',changedDate);await save();await close()
  assert.equal((await get(state.single.id)).date,changedDate)
  checks.push('month entry opens editor and moves event date')
  await open('重复行程验收','.entry')
  assert.equal(await js(`document.querySelector('#event-edit-date').value`),state.series.date)
  assert((await js(`document.querySelector('.edit-scope').textContent`)).includes('整个系列'))
  await fill('event-edit-title','已修改的重复系列');await save()
  assert.equal((await get(state.series.id)).recur_rrule,state.series.recur_rrule)
  await js(`document.documentElement.setAttribute('data-theme','dark')`);win.setSize(900,900);await shot('calendar-edit-dark-narrow')
  assert(await js(`(()=>{const r=document.querySelector('.note').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&document.querySelector('.note').scrollWidth<=document.querySelector('.note').clientWidth})()`))
  await close();await win.reload();await wait(`!!document.querySelector('[data-mode="month"]')`)
  await js(`document.querySelector('[data-mode="month"]').click()`);await open('已修改的行程','.entry')
  assert.equal(await js(`document.querySelector('#event-edit-notes').value`),'修改后备注')
  checks.push('series edit retains anchor and recurrence; reload restores edited details; narrow dark form fits')
  assert.deepEqual(errors,[])
  fs.writeFileSync(path.join(qa,'calendar-ui.json'),JSON.stringify({passed:true,checks,errors},null,2))
  win.destroy();console.log('CALENDAR_NATIVE_PASS');app.exit(0)
 }catch(e){console.error(e.stack);await shot('calendar-failure');fs.writeFileSync(path.join(qa,'calendar-failure.json'),JSON.stringify({error:String(e),errors},null,2));app.exit(1)}
})
