const { app, BrowserWindow } = require('electron')
const fs = require('node:fs'), path = require('node:path'), os = require('node:os'), assert = require('node:assert/strict')
const qa = path.resolve(process.argv[2]), state = JSON.parse(fs.readFileSync(path.join(qa,'bill-ui-state.json'),'utf8'))
const base = `http://127.0.0.1:${state.port}`
app.setPath('userData',fs.mkdtempSync(path.join(os.tmpdir(),'zhishi-bill-render-')))
app.disableHardwareAcceleration()
const delay = ms => new Promise(resolve => setTimeout(resolve,ms))
app.whenReady().then(async () => {
  let win; const errors = []
  try {
    win = new BrowserWindow({width:1450,height:1050,show:false,webPreferences:{offscreen:true,contextIsolation:true,nodeIntegration:false,sandbox:true}})
    win.webContents.on('console-message',(_e,level,message) => { if (level >= 2 && !message.includes('Electron Security Warning')) errors.push(message) })
    const js = code => win.webContents.executeJavaScript(code,true)
    async function wait(code) { for(let i=0;i<500;i++) { if(await js(code)) return; await delay(100) } throw Error('Timeout '+code) }
    const click = selector => js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e||e.disabled)throw Error('Unavailable '+${JSON.stringify(selector)});e.click()})()`)
    const input = (selector,value) => js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing input');e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))})()`)
    const get = url => js(`fetch(${JSON.stringify(url)}).then(r=>r.json())`)
    const snapshot = async name => { await js("document.querySelector('.bills').scrollIntoView({block:'start'})");await delay(400);fs.writeFileSync(path.join(qa,name+'.png'),(await win.webContents.capturePage()).toPNG()) }
    await win.loadURL(base+'/#/ledger')
    await wait("!!document.querySelector('[data-bill-add]') && !!document.querySelector('[data-bill-id]')")
    await click('[data-bill-add]')
    await input('[data-bill-title]','每月房租')
    await input('[data-bill-due]','2026-01-31')
    await input('[data-bill-amount]','2000.00')
    await input('[data-bill-cycle]','monthly')
    await js("document.documentElement.dataset.theme='light'")
    await snapshot('bill-form-light')
    await js("document.documentElement.dataset.theme='dark'")
    await snapshot('bill-form-dark')
    win.setSize(900,1050); await delay(200)
    await snapshot('bill-form-narrow')
    assert(await js('document.documentElement.scrollWidth<=innerWidth'))
    await click('[data-bill-save]')
    await wait("!document.querySelector('[data-bill-save]') && !!document.querySelector('[data-bill-history]')")
    let page = await get('/api/bills'), rent = page.items.find(b=>b.details.title==='每月房租')
    assert(rent); assert.equal((await get('/api/ledger')).total,1)
    const rentSelector = `[data-bill-id="${rent.id}"]`
    await click(rentSelector+' [data-bill-pay]')
    await wait("!!document.querySelector('[data-payment-confirm]')")
    await input('[data-payment-day]','2026-01-31')
    await input('[data-payment-amount]','1999.95')
    await click('[data-payment-confirm]')
    await wait("!document.querySelector('[data-payment-confirm]') && document.querySelector('[data-bill-history]')?.textContent.includes('已确认支付')")
    rent = await get(`/api/bills/${rent.id}`)
    assert.equal(rent.pending.due,'2026-02-28')
    assert.equal((await get('/api/ledger')).total,2)
    await click('[data-bill-skip]')
    await input('[data-skip-reason]','二月免租')
    await click('[data-skip-confirm]')
    await wait("!document.querySelector('[data-skip-confirm]') && document.querySelector('[data-bill-history]')?.textContent.includes('二月免租')")
    rent = await get(`/api/bills/${rent.id}`); assert.equal(rent.pending.due,'2026-03-31')
    await click(rentSelector+' [data-bill-toggle]')
    await wait(`document.querySelector(${JSON.stringify(rentSelector)})?.textContent.includes('已暂停') && !document.querySelector('[data-bill-add]')?.disabled`)
    await js(`[...document.querySelectorAll(${JSON.stringify(rentSelector+' button')})].find(e=>e.textContent==='修改').click()`)
    await wait("!!document.querySelector('[data-bill-save]')")
    assert(await js("document.querySelector('[data-bill-due]').disabled"))
    await input('[data-bill-amount]','2100')
    await click('[data-bill-save]')
    await wait("!document.querySelector('[data-bill-save]') && document.querySelector('[data-bill-history]')?.textContent.includes('2100')")
    await snapshot('bill-results-dark')
    // Create another bill, then associate the actual pre-upgrade entry through the native form.
    await click('[data-bill-add]'); await input('[data-bill-title]','云盘旧账关联')
    await input('[data-bill-due]','2026-01-31'); await input('[data-bill-amount]','12.50'); await input('[data-bill-cycle]','once')
    await click('[data-bill-save]'); await wait("!document.querySelector('[data-bill-save]') && document.querySelector('[data-bill-history]')?.textContent.includes('云盘旧账关联')")
    const cloud = (await get('/api/bills')).items.find(b=>b.details.title==='云盘旧账关联')
    await click(`[data-bill-id="${cloud.id}"] [data-bill-pay]`)
    await wait("!!document.querySelector('[data-payment-confirm]')")
    await input('[data-payment-day]','2026-01-31')
    await input('input[placeholder="未记账则留空"]',String(state.entry_id))
    await click('[data-payment-confirm]')
    await wait("!document.querySelector('[data-payment-confirm]') && document.querySelector('[data-bill-history]')?.textContent.includes('已确认支付')")
    assert.equal((await get('/api/ledger')).total,2)
    // The real scheduler, not a fixture endpoint, supplies this overdue notification.
    await wait(`fetch('/api/notifications').then(r=>r.json()).then(ns=>ns.some(n=>n.target_path==='/ledger?bill=${state.reminder_bill_id}'))`)
    await js("location.hash='/calendar'"); await wait("!document.querySelector('.bills')")
    await click('.bell-wrap .bell')
    await wait("[...document.querySelectorAll('.li-open')].some(e=>e.textContent.includes('查看账单'))")
    await js(`[...document.querySelectorAll('.li-open')].find(e=>e.closest('li')?.textContent.includes('到期提醒验收')).click()`)
    await wait(`location.hash.includes('bill=${state.reminder_bill_id}') && document.querySelector('[data-bill-history]')?.textContent.includes('到期提醒验收')`)
    await win.reload(); await wait("!!document.querySelector('[data-bill-history]')")
    assert.equal((await get(`/api/bills/${rent.id}`)).pending.due,'2026-03-31')
    assert.deepEqual(errors,[])
    fs.writeFileSync(path.join(qa,'bill-ui-result.json'),JSON.stringify({passed:true,rent_id:rent.id,cloud_id:cloud.id,
      checks:['native create','light/dark/narrow','actual payment creates one entry','month-end anchor','skip reason','pause','edit preserves history','link pre-upgrade ledger without duplication','real scheduler notification opens exact bill','reload'],errors},null,2))
    console.log('BILL_NATIVE_UI_PASS');app.exit(0)
  } catch(error) {
    console.error(error.stack)
    if(win)fs.writeFileSync(path.join(qa,'bill-ui-failure.png'),(await win.webContents.capturePage()).toPNG())
    fs.writeFileSync(path.join(qa,'bill-ui-failure.json'),JSON.stringify({error:String(error),errors},null,2))
    app.exit(1)
  }
})
