const { app, BrowserWindow } = require('electron')
const fs = require('node:fs'), path = require('node:path'), os = require('node:os'), assert = require('node:assert/strict')
const qa = path.resolve(process.argv[2])
const state = JSON.parse(fs.readFileSync(path.join(qa, 'web-ui-state.json'), 'utf8'))
const base = `http://127.0.0.1:${state.port}`, project = `/api/research/projects/${state.project_id}`
app.setPath('userData', fs.mkdtempSync(path.join(os.tmpdir(), 'zhishi-web-render-')))
app.disableHardwareAcceleration()
const delay = ms => new Promise(resolve => setTimeout(resolve, ms))
app.whenReady().then(async () => {
  const errors = []
  let win
  try {
    win = new BrowserWindow({ width: 1450, height: 1000, show: false, webPreferences: { offscreen: true, contextIsolation: true, nodeIntegration: false, sandbox: true } })
    win.webContents.on('console-message', (_e, level, message) => { if (level >= 2 && !message.includes('Electron Security Warning')) errors.push(message) })
    const js = code => win.webContents.executeJavaScript(code, true)
    async function wait(code) { for (let i = 0; i < 300; i++) { if (await js(code)) return; await delay(100) } throw Error('Timeout ' + code) }
    async function click(label, scope = 'document') {
      await js(`(()=>{const b=[...${scope}.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(label)});if(!b||b.disabled)throw Error('Unavailable button');b.click()})()`)
    }
    async function input(selector, value) {
      await js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))})()`)
    }
    async function shot(name, selector) {
      if (selector) await js(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'start'})`)
      await delay(350)
      fs.writeFileSync(path.join(qa, name + '.png'), (await win.webContents.capturePage()).toPNG())
    }
    await win.loadURL(base + `/#/research?project=${state.project_id}`)
    await wait(`!!document.querySelector('[data-refresh-source="${state.source_id}"]')`)
    await js(`document.querySelector('[data-refresh-source="${state.source_id}"]').click()`)
    await wait(`document.querySelectorAll('.source').length===2 && document.querySelector('.source .badge')?.textContent==='已获取正文' && !document.querySelector('[data-refresh-source="${state.source_id}"]')`)
    assert(await js(`document.querySelectorAll('.source')[1].textContent.includes('历史版本')`))
    const detail = await js(`fetch(${JSON.stringify(project)}).then(r=>r.json())`)
    const current = detail.sources.find(s => !s.superseded_by)
    assert.equal(current.document.indexed_chars, state.body_chars)
    assert.notEqual(current.library_file_id, state.original_file_id)
    await js(`document.documentElement.dataset.theme='light'`)
    await shot('web-project-light', '.source')
    await input('.material-search input', '最后练习')
    await click('检索正文')
    await wait(`document.querySelector('.hit')?.textContent.includes('整理对照表')`)
    await js(`document.querySelector('.hit a').click()`)
    await wait(`[...document.querySelectorAll('.material-reader pre')].some(e=>e.textContent.includes('整理对照表'))`)
    assert(await js(`location.hash.includes('file=${current.library_file_id}')`))
    await shot('web-tail-light', '.material-reader')
    await input('.material-reader nav input', '1')
    await click('跳转')
    await wait(`document.querySelector('.material-reader .hint')?.textContent.includes('当前展示 1–3')`)
    await click('继续阅读')
    await wait(`document.querySelector('.material-reader .hint')?.textContent.includes('当前展示 4–6')`)
    await js(`location.hash='/research?project=${state.project_id}'`)
    await wait(`!!document.querySelector('.task blockquote a')`)
    await js(`document.querySelector('.task blockquote a').click()`)
    await wait(`document.querySelector('.material-reader pre')?.textContent.includes('原版引用')`)
    assert(await js(`location.hash.includes('file=${state.original_file_id}')&&location.hash.includes('revision=${state.original_revision}')`))
    await js(`location.hash='/research?project=${state.project_id}'`)
    await wait(`!!document.querySelector('[data-refresh-source="${current.id}"]')`)
    await js(`document.querySelector('[data-refresh-source="${current.id}"]').click()`)
    await wait(`!document.querySelector('[data-refresh-source="${current.id}"]')?.disabled && document.querySelectorAll('.source').length===2`)
    await js(`document.documentElement.dataset.theme='dark'`)
    await shot('web-project-dark', '.source')
    win.setSize(900, 1000)
    await delay(250)
    await shot('web-project-narrow', '.source')
    assert(await js(`document.documentElement.scrollWidth<=innerWidth`), 'horizontal overflow')
    assert.deepEqual(errors, [])
    fs.writeFileSync(path.join(qa, 'web-ui-result.json'), JSON.stringify({ passed: true, current_source_id: current.id, checks: ['refresh old excerpt', 'late-text search and read', 'jump and continue', 'old task citation unchanged', 'same-body refresh deduplicated', 'light/dark/narrow'], errors }, null, 2))
    console.log('WEB_NATIVE_UI_PASS')
    app.exit(0)
  } catch (error) {
    console.error(error.stack)
    if (win) fs.writeFileSync(path.join(qa, 'web-ui-failure.png'), (await win.webContents.capturePage()).toPNG())
    fs.writeFileSync(path.join(qa, 'web-ui-failure.json'), JSON.stringify({ error: String(error), errors }, null, 2))
    app.exit(1)
  }
})
