const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { createDiagnostics } = require('../diagnostics')

test('desktop diagnostics retain only fixed events and numeric codes, with bounded rotation', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'zhishi-diagnostic-test-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const record = createDiagnostics(root, '2.20.0')
  record('startup')
  record('renderer_gone', -1073741819)
  record('startup_failed', 'SECRET private path')
  record('SECRET private event')
  const file = path.join(root, 'v2', 'logs', 'desktop-diagnostics.jsonl')
  const text = fs.readFileSync(file, 'utf8')
  assert.equal(text.includes('SECRET'), false)
  const rows = text.trim().split('\n').map(JSON.parse)
  assert.equal(rows.length, 3)
  assert.equal(rows[1].status_code, -1073741819)
  fs.appendFileSync(file, 'x'.repeat(512 * 1024))
  record('window_loaded')
  assert.ok(fs.existsSync(file + '.1'))
  assert.equal(JSON.parse(fs.readFileSync(file, 'utf8')).event, 'window_loaded')
})
