/** Strictly parse the calendar occurrence links generated by reminder records. */
export function parseCalendarTarget(value?: string | null): { date: string; eventId: number } | undefined {
  const match = /^\/calendar\?date=(\d{4}-\d{2}-\d{2})&event=([1-9]\d*)$/.exec(value ?? '')
  if (!match) return
  const iso = match[1]!, id = Number(match[2])
  const day = new Date(`${iso}T12:00:00`)
  if (!Number.isSafeInteger(id) || !Number.isFinite(day.getTime()) || day.getFullYear() < 1) return
  const canonical = `${String(day.getFullYear()).padStart(4, '0')}-${String(day.getMonth() + 1).padStart(2, '0')}-${String(day.getDate()).padStart(2, '0')}`
  if (canonical !== iso) return
  return { date: iso, eventId: id }
}
